Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2018-12, with the labels that each got.

#712 Add a Contribution Guide with detailed instructions for new contributors
  .github/ISSUE_TEMPLATE.md
  CONTRIBUTING.md
Labels: documentation

#714 Remove deprecated copy method
  addon/components/base/bs-button-group.js
Labels: bug

#718 Fix layout of checkbox elements for Bootstrap 4
  addon/components/base/bs-form/element/layout/horizontal.js
  addon/components/base/bs-form/element/layout/horizontal/checkbox.js
  addon/components/bs3/bs-form/element/layout/horizontal.js
  addon/components/bs3/bs-form/element/layout/horizontal/checkbox.js
  addon/components/bs4/bs-form/element/label.js
  addon/components/bs4/bs-form/element/layout/horizontal.js
  addon/components/bs4/bs-form/element/layout/horizontal/checkbox.js
  addon/components/bs4/bs-form/group.js
  addon/templates/components/bs4/bs-form/element/layout/horizontal/checkbox.hbs
  addon/templates/components/bs4/bs-form/element/layout/vertical/checkbox.hbs
  fastboot-tests/form-test.js
  tests/integration/components/bs-form/group-test.js
Labels: Bootstrap 4, bug

#719 Add docs section about supplementary addons
  tests/dummy/app/router.js
  tests/dummy/app/templates/addons.hbs
  tests/dummy/app/templates/application.hbs
Labels: documentation

#726 Add support for radio form elements
  addon/components/base/bs-form/element.js
  addon/components/base/bs-form/element/control/radio.js
  addon/components/bs3/bs-form/element/control/radio.js
  addon/components/bs4/bs-form/element/control/radio.js
  addon/templates/components/bs3/bs-form/element/control/radio.hbs
  addon/templates/components/bs4/bs-form/element/control/radio.hbs
  app/components/bs-form/element/control/radio.js
  tests/dummy/app/controllers/demo/forms.js
  tests/dummy/app/templates/demo/forms.hbs
  tests/integration/components/bs-form/element-test.js
Labels: enhancement

#727 Update all dependencies
  .eslintignore
  .eslintrc.js
  .gitignore
  .npmignore
  .travis.yml
  config/ember-try.js
  node-tests/blueprints/ember-bootstrap-test.js
  package.json
  tests/dummy/config/environment.js
  yarn.lock
Labels: internal

#730 Form submission state reflects Promise returned by onInvalid action
  addon/components/base/bs-form.js
  tests/integration/components/bs-form-test.js
Labels: bug

#735 Fix popover clicks
  addon/components/base/bs-contextual-help.js
  tests/integration/components/bs-popover-test.js
Labels: bug
