Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2019-05, with the labels that each got.

#701 Modal header component yields title and close components
  addon/components/base/bs-modal/header.js
  addon/templates/components/bs3/bs-modal/header.hbs
  addon/templates/components/bs4/bs-modal/header.hbs
  tests/integration/components/bs-modal/header-test.js
Labels: enhancement

#778 Updated demo examples to angle brackets syntax
  .gitignore
  tests/dummy/app/templates/demo.hbs
  tests/dummy/app/templates/demo/accordion.hbs
  tests/dummy/app/templates/demo/alert.hbs
  tests/dummy/app/templates/demo/button-group.hbs
  tests/dummy/app/templates/demo/button.hbs
  tests/dummy/app/templates/demo/carousel.hbs
  tests/dummy/app/templates/demo/collapse.hbs
  tests/dummy/app/templates/demo/dropdown.hbs
  tests/dummy/app/templates/demo/index.hbs
  tests/dummy/app/templates/demo/modal.hbs
  tests/dummy/app/templates/demo/navbars.hbs
  tests/dummy/app/templates/demo/navs.hbs
  tests/dummy/app/templates/demo/popover.hbs
  tests/dummy/app/templates/demo/progress.hbs
  tests/dummy/app/templates/demo/tabs.hbs
  tests/dummy/app/templates/demo/tabs/index.hbs
  tests/dummy/app/templates/demo/tabs/other.hbs
  tests/dummy/app/templates/demo/tooltip.hbs
  yarn.lock
Labels: documentation

#809 Propagate `disabled` and `readonly` property to all yielded form elements
  addon/components/base/bs-form.js
  addon/templates/components/common/bs-form.hbs
  tests/integration/components/bs-form-test.js
Labels: enhancement

#777 Update API docs for Angle Bracket Invocation
  addon/components/base/bs-accordion.js
  addon/components/base/bs-alert.js
  addon/components/base/bs-button-group.js
  addon/components/base/bs-button.js
  addon/components/base/bs-carousel.js
  addon/components/base/bs-carousel/slide.js
  addon/components/base/bs-collapse.js
  addon/components/base/bs-contextual-help.js
  addon/components/base/bs-dropdown.js
  addon/components/base/bs-form.js
  addon/components/base/bs-form/element.js
  addon/components/base/bs-form/group.js
  addon/components/base/bs-modal-simple.js
  addon/components/base/bs-modal.js
  addon/components/base/bs-nav.js
  addon/components/base/bs-navbar.js
  addon/components/base/bs-popover.js
  addon/components/base/bs-progress.js
  addon/components/base/bs-tab.js
  addon/components/base/bs-tooltip.js
Labels: documentation

#815 Fixed modal error when clicking on SVG in IE11
  addon/components/base/bs-modal/dialog.js
Labels: bug

#783 Add linkTo support for nav.item, deprecate nav.link-to
  addon/components/base/bs-nav.js
  addon/components/base/bs-nav/item.js
  addon/components/base/bs-nav/link-to.js
  addon/components/base/bs-navbar.js
  addon/components/base/bs-navbar/nav-item.js
  addon/components/base/bs-tab.js
  addon/components/bs3/bs-navbar/nav-item.js
  addon/components/bs4/bs-nav/item.js
  addon/components/bs4/bs-navbar/nav-item.js
  addon/templates/components/bs3/bs-navbar.hbs
  addon/templates/components/bs4/bs-navbar.hbs
  addon/templates/components/common/bs-nav/item.hbs
  app/components/bs-navbar/nav-item.js
  package.json
  tests/acceptance/bs-nav-link-test.js
  tests/dummy/app/templates/acceptance/link.hbs
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/demo.hbs
  tests/dummy/app/templates/demo/navbars.hbs
  tests/dummy/app/templates/demo/navs.hbs
  tests/dummy/app/templates/demo/tabs.hbs
  tests/helpers/setup-no-deprecations.js
  tests/integration/components/bs-nav-test.js
  tests/integration/components/bs-nav/item-test.js
  tests/integration/components/bs-nav/link-to-test.js
  tests/integration/components/bs-navbar-test.js
  yarn.lock
Labels: enhancement

#818 Form asserts for valid `formLayout` value
  addon/components/base/bs-form.js
  addon/components/bs3/bs-form.js
  tests/integration/components/bs-form-test.js
Labels: bug

#789 Yield submit action from BsForm
  addon/components/base/bs-form.js
  addon/templates/components/common/bs-form.hbs
  tests/integration/components/bs-form-test.js
Labels: enhancement
