Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2019-01, with the labels that each got.

#738 Modal should not violate CSP style-src 'none'
  addon/components/base/bs-modal/dialog.js
Labels: bug

#737 Form: click on input group button should not show validations
  addon/components/base/bs-form/element.js
  addon/components/bs3/bs-form/element.js
  addon/components/bs4/bs-form/element.js
  tests/helpers/bootstrap-test.js
  tests/integration/components/bs-form/element-test.js
Labels: bug

#744 Fix failing build under node 6
  package.json
  yarn.lock
Labels: internal

#745 Fix broken tooltips/popovers in Ember 3.8.0(-beta)
  addon/components/base/bs-contextual-help.js
  addon/templates/components/common/bs-popover.hbs
  addon/templates/components/common/bs-tooltip.hbs
  addon/utils/get-parent.js
Labels: bug

#746 CSP: refactor to not require `style-src 'unsafe-inline` and add test coverage
  addon/components/base/bs-collapse.js
  addon/components/base/bs-progress/bar.js
  package.json
  tests/dummy/config/environment.js
  tests/helpers/setup-stylesheet-support.js
  tests/integration/components/bs-popover-test.js
  tests/integration/components/bs-progress-test.js
  tests/integration/components/bs-tooltip-test.js
  tests/test-helper.js
  yarn.lock
Labels: enhancement

#741 Add option to hide all validations after form submission
  addon/components/base/bs-form.js
  addon/components/base/bs-form/element.js
  tests/integration/components/bs-form-test.js
Labels: enhancement
