Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2019-08, with the labels that each got.

#862 BsForm should not catch errors thrown by onSubmit action
  addon/components/base/bs-form.js
  tests/integration/components/bs-form-test.js
Labels: breaking, bug

#864 Refactored mixins
  addon/components/base/bs-accordion.js
  addon/components/base/bs-accordion/item.js
  addon/components/base/bs-alert.js
  addon/components/base/bs-button-group.js
  addon/components/base/bs-button.js
  addon/components/base/bs-carousel/slide.js
  addon/components/base/bs-contextual-help.js
  addon/components/base/bs-dropdown/button.js
  addon/components/base/bs-dropdown/toggle.js
  addon/components/base/bs-form/element/control/checkbox.js
  addon/components/base/bs-form/element/control/input.js
  addon/components/base/bs-form/element/control/textarea.js
  addon/components/base/bs-modal.js
  addon/components/base/bs-nav/item.js
  addon/components/base/bs-navbar.js
  addon/components/base/bs-progress/bar.js
  addon/components/base/bs-tab.js
  addon/components/base/bs-tab/pane.js
  addon/components/bs3/bs-accordion/item.js
  addon/components/bs3/bs-button.js
  addon/components/bs3/bs-form/group.js
  addon/components/bs3/bs-progress/bar.js
  addon/components/bs4/bs-accordion/item.js
  addon/components/bs4/bs-form/element/control/checkbox.js
  addon/components/bs4/bs-form/element/control/input.js
  addon/components/bs4/bs-form/element/control/textarea.js
  addon/components/bs4/bs-progress/bar.js
  addon/mixins/control-attributes.js
  addon/mixins/control-validation.js
  addon/mixins/dropdown-toggle.js
  addon/mixins/size-class.js
  addon/mixins/sub-component.js
  addon/mixins/transition-support.js
  addon/mixins/type-class.js
  addon/utils/cp/form-validation-class.js
  addon/utils/cp/listen-to.js
  addon/utils/cp/overrideable.js
  addon/utils/cp/size-class.js
  addon/utils/cp/type-class.js
  addon/utils/cp/uses-transition.js
  addon/utils/is-fastboot.js
  yarn.lock
Labels: internal

#861 Change nav.item link support to match Ember's `<LinkTo>`
  addon/components/base/bs-nav.js
  addon/components/base/bs-nav/item.js
  addon/templates/components/common/bs-nav/item.hbs
  package.json
  tests/acceptance/bs-nav-link-test.js
  tests/dummy/app/templates/acceptance/link.hbs
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/demo.hbs
  tests/dummy/app/templates/demo/navbars.hbs
  tests/dummy/app/templates/demo/navs.hbs
  tests/dummy/app/templates/demo/tabs.hbs
  tests/integration/components/bs-nav/item-test.js
  yarn.lock
Labels: breaking, enhancement

#872 Fix form validation for Ember 3.12-beta
  addon/components/base/bs-form.js
  addon/components/base/bs-form/element.js
Labels: bug

#877 support hash helper used as form model
  addon/templates/components/common/bs-form.hbs
  tests/integration/components/bs-form-test.js
Labels: bug

#871 Workaround nav.item not applying `active` class correctly due to Ember 3.12-beta bug
  addon/components/base/bs-nav/item.js
Labels: bug

#879 Revert the link support of nav.item and the deprecation of nav.link-to
  addon/components/base/bs-nav.js
  addon/components/base/bs-nav/item.js
  addon/components/base/bs-nav/link-to.js
  addon/components/base/bs-navbar.js
  addon/components/base/bs-navbar/nav-item.js
  addon/components/base/bs-tab.js
  addon/components/bs3/bs-navbar/nav-item.js
  addon/components/bs4/bs-navbar/nav-item.js
  addon/templates/components/bs3/bs-navbar.hbs
  addon/templates/components/bs4/bs-navbar.hbs
  addon/templates/components/common/bs-nav/item.hbs
  package.json
  tests/acceptance/bs-nav-link-test.js
  tests/dummy/app/controllers/application.js
  tests/dummy/app/router.js
  tests/dummy/app/templates/acceptance/link.hbs
  tests/dummy/app/templates/acceptance/linkto.hbs
  tests/dummy/app/templates/application.hbs
  tests/dummy/app/templates/demo.hbs
  tests/dummy/app/templates/demo/navbars.hbs
  tests/dummy/app/templates/demo/navs.hbs
  tests/dummy/app/templates/demo/tabs.hbs
  tests/integration/components/bs-nav-test.js
  tests/integration/components/bs-nav/item-test.js
  tests/integration/components/bs-nav/link-to-test.js
  tests/integration/components/bs-navbar-test.js
  yarn.lock
Labels: breaking

#884 Fix FastBoot rendering of opened modals
  addon/components/bs3/bs-modal/dialog.js
  addon/components/bs4/bs-modal/dialog.js
  tests/fastboot/modal-test.js
  tests/integration/components/bs-modal-simple-test.js
Labels: bug

#885 Update docs to show angle bracket syntax for dropdown link-to
  addon/components/base/bs-dropdown.js
  addon/components/base/bs-nav.js
  addon/components/base/bs-navbar.js
  tests/dummy/app/templates/demo/dropdown.hbs
  tests/dummy/app/templates/demo/navbars.hbs
  tests/dummy/app/templates/demo/navs.hbs
  tests/integration/components/bs-dropdown/menu/link-to-test.js
Labels: documentation

#886 Add `linkTo` alias for yielded nav and dropdown link components, for better angle brackets style
  addon/components/base/bs-dropdown.js
  addon/components/base/bs-nav.js
  addon/components/base/bs-navbar.js
  addon/components/base/bs-tab.js
  addon/templates/components/bs3/bs-dropdown/menu.hbs
  addon/templates/components/bs4/bs-dropdown/menu.hbs
  addon/templates/components/common/bs-nav.hbs
  tests/integration/components/bs-dropdown/menu-test.js
  tests/integration/components/bs-nav-test.js
Labels: enhancement
