Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2019-07, with the labels that each got.

#847 FormElement: revert passing HTML attributes to its control component w/ angle brackets
  addon/components/base/bs-form/element.js
  addon/templates/components/common/bs-form/element.hbs
  tests/integration/components/bs-form/element-test.js
Labels: bug

#851 Render Modals, Tooltips and Popovers in a wormhole even in tests
  addon/components/base/bs-contextual-help.js
  addon/components/base/bs-dropdown/menu.js
  addon/components/base/bs-modal.js
  addon/templates/components/bs3/bs-dropdown/menu.hbs
  addon/templates/components/bs4/bs-dropdown/menu.hbs
  addon/templates/components/common/bs-popover.hbs
  addon/templates/components/common/bs-popover/element.hbs
  addon/templates/components/common/bs-tooltip.hbs
  addon/templates/components/common/bs-tooltip/element.hbs
  addon/utils/dom.js
  tests/dummy/config/optional-features.json
  tests/integration/components/bs-modal-simple-test.js
  tests/integration/components/bs-popover-test.js
  tests/integration/components/bs-tooltip-test.js
Labels: breaking

#859 Warn if configured to import Glyphicon but Boostrap 4 is used
  blueprints/ember-bootstrap/index.js
  index.js
Labels: enhancement
