Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2019-12, with the labels that each got.

#933 Deprecate arguments whose only purpose is supporting HTML attributes
  addon/components/base/bs-button.js
  addon/components/base/bs-form/element.js
  addon/templates/components/common/bs-modal/footer.hbs
  tests/helpers/setup-no-deprecations.js
  tests/integration/components/bs-button-test.js
  tests/integration/components/bs-form-test.js
  tests/integration/components/bs-form/element-test.js
Labels: enhancement

#943 Update to Ember 3.14
  .eslintrc.js
  .npmignore
  addon/components/base/bs-carousel.js
  addon/components/base/bs-form/element.js
  addon/components/base/bs-tab/pane.js
  addon/mixins/component-child.js
  addon/mixins/component-parent.js
  addon/utils/cp/form-validation-class.js
  package.json
  testem.js
  tests/dummy/app/router.js
  yarn.lock
Labels: internal

#942 Fix keyboard control of Dropdowns rendered in a wormhole
  addon/components/base/bs-dropdown.js
  addon/components/base/bs-dropdown/menu.js
  addon/templates/components/bs3/bs-dropdown/menu.hbs
  addon/templates/components/bs4/bs-dropdown/menu.hbs
  tests/integration/components/bs-dropdown-test.js
Labels: a11y, bug

#947 Fix typo (Pikaday instead of PiCkaday)
  addon/components/base/bs-form/element.js
Labels: documentation
