Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2019-06, with the labels that each got.

#820 Form validations are shown only after an eventual promise returned from onInvalid action resolves
  addon/components/base/bs-form.js
  tests/integration/components/bs-form-test.js
Labels: breaking, enhancement

#819 Add dynamic snippets to demo app
  ember-cli-build.js
  package.json
  tests/dummy/app/controllers/demo/progress.js
  tests/dummy/app/helpers/dynamic-code-snippet.js
  tests/dummy/app/styles/app.scss
  tests/dummy/app/styles/highlight-style.scss
  tests/dummy/app/templates/components/code-snippet.hbs
  tests/dummy/app/templates/demo/alert.hbs
  tests/dummy/app/templates/demo/carousel.hbs
  tests/dummy/app/templates/demo/collapse.hbs
  tests/dummy/app/templates/demo/forms.hbs
  tests/dummy/app/templates/demo/modal.hbs
  tests/dummy/app/templates/demo/navbars.hbs
  tests/dummy/app/templates/demo/navs.hbs
  tests/dummy/app/templates/demo/popover.hbs
  tests/dummy/app/templates/demo/progress.hbs
  tests/dummy/app/templates/demo/tooltip.hbs
  yarn.lock
Labels: documentation

#834 Form's and Button's preventConcurrency defaults to true
  addon/components/base/bs-button.js
  addon/components/base/bs-form.js
  tests/integration/components/bs-button-test.js
  tests/integration/components/bs-form-test.js
Labels: breaking, enhancement

#840 Update all dependencies
  .eslintrc.js
  node-tests/lint-tests.js
  package.json
  tests/dummy/config/environment.js
  yarn.lock
Labels: internal

#842 Button is disabled by default if in pending state
  addon/components/base/bs-button.js
  tests/integration/components/bs-button-test.js
Labels: breaking, enhancement
