Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2019-02, with the labels that each got.

#753 Forms use the set function of the model if it is present
  addon/components/base/bs-form.js
Labels: enhancement

#754 Fix transition for bs-collapse
  addon/components/base/bs-collapse.js
Labels: bug

#758 tests: remove work-a-round for qunit test runner CSP violation
  tests/dummy/config/environment.js
  tests/test-helper.js
  yarn.lock
Labels: internal

#732 Form yields isSubmitted and isRejected properties
  addon/components/base/bs-form.js
  addon/components/base/bs-form/element.js
  addon/templates/components/common/bs-form.hbs
  tests/integration/components/bs-form-test.js
Labels: enhancement

#756 Fixed deprecations in Ember 3.8.0-beta and 3.9-canary
  addon/components/base/bs-button.js
  addon/components/base/bs-carousel.js
  addon/components/base/bs-carousel/slide.js
  addon/components/base/bs-contextual-help.js
  addon/components/base/bs-dropdown.js
  addon/components/base/bs-modal.js
  addon/components/base/bs-nav/item.js
  addon/components/base/bs-popover.js
  addon/components/base/bs-tooltip.js
  addon/components/bs3/bs-form/element.js
  addon/components/bs4/bs-form/element.js
  addon/templates/components/common/bs-modal-simple.hbs
  addon/utils/overrideable-cp.js
  config/ember-try.js
  tests/dummy/config/environment.js
  tests/helpers/setup-no-deprecations.js
  tests/integration/components/bs-accordion-test.js
  tests/integration/components/bs-accordion/item-test.js
  tests/integration/components/bs-alert-test.js
  tests/integration/components/bs-button-group-test.js
  tests/integration/components/bs-button-test.js
  tests/integration/components/bs-carousel-test.js
  tests/integration/components/bs-collapse-test.js
  tests/integration/components/bs-dropdown-test.js
  tests/integration/components/bs-dropdown/button-test.js
  tests/integration/components/bs-dropdown/menu-test.js
  tests/integration/components/bs-dropdown/menu/item-test.js
  tests/integration/components/bs-dropdown/menu/link-to-test.js
  tests/integration/components/bs-dropdown/toggle-test.js
  tests/integration/components/bs-form-test.js
  tests/integration/components/bs-form/element-test.js
  tests/integration/components/bs-form/element/control/checkbox-test.js
  tests/integration/components/bs-form/element/control/input-test.js
  tests/integration/components/bs-form/element/control/textarea-test.js
  tests/integration/components/bs-form/element/errors-test.js
  tests/integration/components/bs-form/element/feedback-icon-test.js
  tests/integration/components/bs-form/element/help-text-test.js
  tests/integration/components/bs-form/element/label-test.js
  tests/integration/components/bs-form/group-test.js
  tests/integration/components/bs-modal-simple-test.js
  tests/integration/components/bs-modal-test.js
  tests/integration/components/bs-modal/footer-test.js
  tests/integration/components/bs-modal/header-test.js
  tests/integration/components/bs-nav-test.js
  tests/integration/components/bs-nav/item-test.js
  tests/integration/components/bs-nav/link-to-test.js
  tests/integration/components/bs-navbar-test.js
  tests/integration/components/bs-navbar/content-test.js
  tests/integration/components/bs-navbar/nav-test.js
  tests/integration/components/bs-navbar/toggle-test.js
  tests/integration/components/bs-popover-test.js
  tests/integration/components/bs-progress-test.js
  tests/integration/components/bs-progress/bar-test.js
  tests/integration/components/bs-tab-test.js
  tests/integration/components/bs-tab/pane-test.js
  tests/integration/components/bs-tooltip-test.js
Labels: bug
