Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2019-04, with the labels that each got.

#794 Add novalidate attribute to forms by default if they support client-side validations
  addon/components/base/bs-form.js
  tests/integration/components/bs-form-test.js
Labels: breaking, enhancement

#802 Allow ember-concurrency 0.8.x - 0.10.x
  package.json
  yarn.lock
Labels: internal

#804 Assertion to prevent setting both property and value on a form element
  addon/components/base/bs-form/element.js
Labels: enhancement
