Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2019-11, with the labels that each got.

#919 onSlideChange action added for bs-carousel
  addon/components/base/bs-carousel.js
  tests/integration/components/bs-carousel-test.js
Labels: enhancement

#923 Add aria-expanded attribute to dropdown toggle
  addon/components/base/bs-dropdown/button.js
  addon/components/base/bs-dropdown/toggle.js
  addon/templates/components/common/bs-dropdown.hbs
  tests/integration/components/bs-dropdown-test.js
Labels: a11y, enhancement

#924 app.options['ember-bootstrap'] may be undefined
  index.js
Labels: bug

#921 Add keyboard control to dropdowns
  addon/components/base/bs-dropdown.js
  addon/components/base/bs-dropdown/button.js
  addon/components/base/bs-dropdown/toggle.js
  addon/templates/components/common/bs-dropdown.hbs
  package.json
  tests/integration/components/bs-dropdown-test.js
  tests/test-helper.js
  yarn.lock
Labels: a11y, enhancement

#926 Add tablist role to <BsTab>
  addon/templates/components/common/bs-tab.hbs
  tests/integration/components/bs-tab-test.js
Labels: a11y, bug

#925 Trap focus inside Modals
  addon/components/base/bs-modal.js
  addon/components/base/bs-modal/dialog.js
  addon/templates/components/common/bs-modal/dialog.hbs
  package.json
  tests/integration/components/bs-modal-simple-test.js
  yarn.lock
Labels: a11y, enhancement
