Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2020-10, with the labels that each got.

#1273 use @embroider/test-setup
  .github/workflows/ci.yml
  config/ember-try.js
  ember-cli-build.js
  package.json
  yarn.lock
Labels: internal

#1275 Enable splattributes on dropdown menu divider and add tests
  addon/components/bs-dropdown/menu/divider.hbs
  tests/integration/components/bs-dropdown/menu/divider-test.js
Labels: bug

#1274 Update contributing docs to account for new @embroider/macros based build setup
  CONTRIBUTING.md
Labels: documentation

#1284 Fix deprecate's own deprecations for Ember canary
  addon/components/bs-contextual-help.js
  addon/utils/deprecate-subclassing.js
Labels: bug

#1283 Apply default values even if undefined is passed, allowing for easy wrapping of components
  addon/components/bs-form.js
  addon/utils/decorators/arg.js
  addon/utils/default-decorator.js
  config/ember-try.js
  ember-cli-build.js
  index.js
  tests/helpers/bootstrap.js
  tests/integration/components/bs-form-test.js
Labels: enhancement

#1306 <BsAccordion> should support @onChange={{undefined}}
  addon/components/bs-accordion.js
  tests/integration/components/bs-accordion-test.js
Labels: bug

#1281 Fixed onDismissed being called twice when visible changes value
  addon/components/bs-alert.js
  tests/integration/components/bs-alert-test.js
Labels: bug

#1279 Refactor Tooltips and Popovers to Glimmer components
  addon/components/bs-contextual-help.js
  addon/components/bs-contextual-help/element.js
  addon/components/bs-popover.hbs
  addon/components/bs-popover.js
  addon/components/bs-popover/element.hbs
  addon/components/bs-popover/element.js
  addon/components/bs-tooltip.hbs
  addon/components/bs-tooltip.js
  addon/components/bs-tooltip/element.hbs
  addon/components/bs-tooltip/element.js
  addon/utils/decorators/arg.js
  addon/utils/dom.js
  package.json
  tests/integration/components/bs-tooltip-test.js
  yarn.lock
Labels: enhancement
