Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2020-06, with the labels that each got.

#1106 Refactor BsModalSimple to not extend from BsModal
  addon/components/bs-modal-simple.js
  addon/components/bs-modal.js
  addon/templates/components/bs-modal-simple.hbs
  addon/templates/components/bs-modal.hbs
  addon/utils/cp/uses-transition.js
  tests/integration/components/bs-modal-simple-test.js
Labels: breaking, internal

#1097 Remove leftover two-way binding of form element's `@value` argument
  addon/components/bs-form/element.js
Labels: breaking, bug

#1107 Render body.modal-open in FastBoot
  addon/components/bs-modal.js
  tests/fastboot/modal-test.js
Labels: enhancement

#1108 Update API docs for FormElement#value
  addon/components/bs-form/element.js
Labels: documentation

#1111 Add codemod link to deprecations
  addon/components/base/bs-button.js
  addon/components/base/bs-form.js
  addon/components/base/bs-form/element.js
Labels: enhancement

#1112 Add codemod link to warnings
  addon/components/bs-button.js
  addon/components/bs-form.js
  addon/components/bs-form/element.js
Labels: enhancement

#1098 Reset style attribute after transition of BsCollapse
  addon/components/bs-collapse.js
  addon/templates/components/bs-collapse.hbs
  addon/utils/transition-end.js
  tests/integration/components/bs-collapse-test.js
Labels: bug

#1104 Remove support for subclassing component classes
  addon/components/bs-accordion.js
  addon/components/bs-accordion/item.js
  addon/components/bs-accordion/item/body.js
  addon/components/bs-accordion/item/title.js
  addon/components/bs-alert.js
  addon/components/bs-button-group.js
  addon/components/bs-button-group/button.js
  addon/components/bs-button.js
  addon/components/bs-carousel.js
  addon/components/bs-carousel/slide.js
  addon/components/bs-collapse.js
  addon/components/bs-dropdown.js
  addon/components/bs-dropdown/button.js
  addon/components/bs-dropdown/menu.js
  addon/components/bs-dropdown/menu/divider.js
  addon/components/bs-dropdown/menu/item.js
  addon/components/bs-dropdown/toggle.js
  addon/components/bs-form.js
  addon/components/bs-form/element/control/checkbox.js
  addon/components/bs-form/element/control/input.js
  addon/components/bs-form/element/control/radio.js
  addon/components/bs-form/element/control/textarea.js
  addon/components/bs-form/element/errors.js
  addon/components/bs-form/element/feedback-icon.js
  addon/components/bs-form/element/help-text.js
  addon/components/bs-form/element/label.js
  addon/components/bs-form/element/layout/horizontal.js
  addon/components/bs-form/element/layout/horizontal/checkbox.js
  addon/components/bs-form/element/layout/vertical.js
  addon/components/bs-form/element/layout/vertical/checkbox.js
  addon/components/bs-form/element/legend.js
  addon/components/bs-modal-simple.js
  addon/components/bs-modal.js
  addon/components/bs-modal/body.js
  addon/components/bs-modal/dialog.js
  addon/components/bs-modal/footer.js
  addon/components/bs-modal/header.js
  addon/components/bs-modal/header/close.js
  addon/components/bs-modal/header/title.js
  addon/components/bs-nav.js
  addon/components/bs-nav/item.js
  addon/components/bs-navbar.js
  addon/components/bs-navbar/content.js
  addon/components/bs-navbar/nav.js
  addon/components/bs-navbar/toggle.js
  addon/components/bs-popover.js
  addon/components/bs-progress.js
  addon/components/bs-progress/bar.js
  addon/components/bs-tab.js
  addon/components/bs-tab/pane.js
  addon/components/bs-tooltip.js
  addon/utils/deprecate-subclassing.js
  tests/integration/components/subclassing-test.js
Labels: breaking

#1114 Add `docs:build` and `docs:serve` scripts, remove publishing of docs from gulpfile
  .npmignore
  docs/.gitignore
  docs/README.md
  docs/public/CNAME
  gulpfile.js
  package.json
  yarn.lock
  yuidoc.json
Labels: internal

#1126 Reenable Embroider tests
  .github/workflows/ci.yml
Labels: internal
