Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2020-02, with the labels that each got.

#983 Fix progress bar role and ARIA attributes
  addon/components/base/bs-progress/bar.js
  tests/integration/components/bs-progress-test.js
Labels: a11y, bug

#982 Fix ARIA role of progress bars, convert to tag-less / outerHTML component
  addon/components/base/bs-progress.js
  addon/components/base/bs-progress/bar.js
  addon/components/bs3/bs-progress/bar.js
  addon/components/bs4/bs-progress/bar.js
  addon/templates/components/bs3/bs-progress/bar.hbs
  addon/templates/components/bs4/bs-progress/bar.hbs
  addon/templates/components/common/bs-progress.hbs
  addon/templates/components/common/bs-progress/bar.hbs
  package.json
  tests/integration/components/bs-progress-test.js
  tests/integration/components/bs-progress/bar-test.js
  yarn.lock
Labels: bug, internal

#980 Convert Button and Dropdown to tag-less / outerHTML component
  addon/components/base/bs-button.js
  addon/components/base/bs-dropdown.js
  addon/components/base/bs-dropdown/button.js
  addon/components/base/bs-dropdown/menu/divider.js
  addon/components/base/bs-dropdown/menu/item.js
  addon/components/base/bs-dropdown/toggle.js
  addon/components/bs3/bs-dropdown.js
  addon/components/bs3/bs-dropdown/menu/divider.js
  addon/components/bs3/bs-dropdown/menu/item.js
  addon/components/bs4/bs-dropdown.js
  addon/components/bs4/bs-dropdown/menu/divider.js
  addon/components/bs4/bs-dropdown/menu/item.js
  addon/components/bs4/bs-dropdown/toggle.js
  addon/templates/components/bs3/bs-dropdown.hbs
  addon/templates/components/bs3/bs-dropdown/menu.hbs
  addon/templates/components/bs3/bs-dropdown/menu/divider.hbs
  addon/templates/components/bs3/bs-dropdown/menu/item.hbs
  addon/templates/components/bs3/bs-dropdown/toggle.hbs
  addon/templates/components/bs4/bs-dropdown.hbs
  addon/templates/components/bs4/bs-dropdown/menu.hbs
  addon/templates/components/bs4/bs-dropdown/menu/divider.hbs
  addon/templates/components/bs4/bs-dropdown/menu/item.hbs
  addon/templates/components/bs4/bs-dropdown/toggle.hbs
  addon/templates/components/common/bs-button.hbs
  addon/templates/components/common/bs-dropdown.hbs
  addon/templates/components/common/bs-dropdown/button.hbs
  addon/templates/components/common/bs-nav.hbs
  package.json
  tests/integration/components/bs-button-test.js
  tests/integration/components/bs-dropdown/button-test.js
  tests/integration/components/bs-dropdown/menu-test.js
  tests/integration/components/bs-dropdown/toggle-test.js
  yarn.lock
Labels: internal

#981 Convert Modals to tag-less / outerHTML component
  addon/components/base/bs-modal.js
  addon/components/base/bs-modal/body.js
  addon/components/base/bs-modal/dialog.js
  addon/components/base/bs-modal/footer.js
  addon/components/base/bs-modal/header.js
  addon/components/base/bs-modal/header/close.js
  addon/components/base/bs-modal/header/title.js
  addon/components/bs3/bs-modal/dialog.js
  addon/components/bs4/bs-modal/dialog.js
  addon/components/bs4/bs-modal/header/title.js
  addon/templates/components/bs3/bs-modal/dialog.hbs
  addon/templates/components/bs3/bs-modal/header.hbs
  addon/templates/components/bs3/bs-modal/header/title.hbs
  addon/templates/components/bs4/bs-modal/dialog.hbs
  addon/templates/components/bs4/bs-modal/header.hbs
  addon/templates/components/bs4/bs-modal/header/title.hbs
  addon/templates/components/common/bs-modal-simple.hbs
  addon/templates/components/common/bs-modal.hbs
  addon/templates/components/common/bs-modal/body.hbs
  addon/templates/components/common/bs-modal/dialog.hbs
  addon/templates/components/common/bs-modal/footer.hbs
  addon/templates/components/common/bs-modal/header/close.hbs
  addon/templates/components/common/bs-modal/header/title.hbs
  package.json
Labels: internal

#988 Convert Navs to tag-less / outerHTML component
  addon/components/base/bs-nav.js
  addon/components/base/bs-nav/item.js
  addon/components/base/bs-navbar/nav.js
  addon/components/bs3/bs-nav.js
  addon/components/bs4/bs-nav.js
  addon/components/bs4/bs-nav/item.js
  addon/templates/components/bs3/bs-nav.hbs
  addon/templates/components/bs3/bs-nav/item.hbs
  addon/templates/components/bs4/bs-nav.hbs
  addon/templates/components/bs4/bs-nav/item.hbs
  addon/templates/components/common/bs-nav.hbs
  addon/templates/components/common/bs-nav/item.hbs
Labels: internal

#996 Convert Collapse to tag-less / outerHTML component
  addon/components/base/bs-accordion/item/body.js
  addon/components/base/bs-collapse.js
  addon/components/base/bs-navbar/content.js
  addon/components/bs3/bs-collapse.js
  addon/components/bs4/bs-collapse.js
  addon/templates/components/bs3/bs-accordion/item/body.hbs
  addon/templates/components/bs4/bs-accordion/item/body.hbs
  addon/templates/components/common/bs-collapse.hbs
  addon/templates/components/common/bs-navbar/content.hbs
Labels: internal

#1004 Drop deprecated arguments for html attributes of form components
  addon/components/base/bs-button.js
  addon/components/base/bs-form.js
  addon/components/base/bs-form/element.js
  addon/components/base/bs-form/element/control/checkbox.js
  addon/components/base/bs-form/element/control/input.js
  addon/components/base/bs-form/element/control/textarea.js
  addon/templates/components/common/bs-button.hbs
  addon/templates/components/common/bs-form/element.hbs
  tests/integration/components/bs-button-test.js
  tests/integration/components/bs-form-test.js
  tests/integration/components/bs-form/element-test.js
Labels: breaking

#1009 Fix bs-carousel with async observers
  addon/components/base/bs-carousel/slide.js
  tests/integration/components/bs-carousel-test.js
Labels: bug

#987 deprecate required arg of <BsForm::Element>
  addon/components/base/bs-form/element.js
  tests/integration/components/bs-form/element-test.js
Labels: enhancement

#1011 Fix a typo in deprecation message
  addon/components/base/bs-form/element.js
Labels: bug
