Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2020-12, with the labels that each got.

#1349 Allow Embroider tests to fail
  .github/workflows/ci.yml
Labels: internal

#1365 <BsDropdown> should use defaultValue if @htmlTag is undefined
  addon/components/bs-dropdown.js
Labels: bug

#1364 <BsForm> demo uses properties which have been removed in v4
  docs/app/templates/demo/forms.hbs
Labels: documentation

#1370 Fix modal not receiving focus
  addon/components/bs-modal/dialog.hbs
  tests/dummy/app/templates/fastboot/modal.hbs
  tests/integration/components/bs-modal-simple-test.js
Labels: bug

#1369 Fix attaching to targets that are rendered *after* the tooltip/popover
  addon/components/bs-contextual-help.js
  tests/integration/components/bs-tooltip-test.js
Labels: bug

#1282 Refactor Modals to Glimmer components
  addon/components/-bs-modal-simple.js
  addon/components/bs-modal-simple.hbs
  addon/components/bs-modal-simple.js
  addon/components/bs-modal.hbs
  addon/components/bs-modal.js
  addon/components/bs-modal/-body.js
  addon/components/bs-modal/-footer.js
  addon/components/bs-modal/-header.js
  addon/components/bs-modal/body.js
  addon/components/bs-modal/dialog.hbs
  addon/components/bs-modal/dialog.js
  addon/components/bs-modal/footer.hbs
  addon/components/bs-modal/footer.js
  addon/components/bs-modal/header.hbs
  addon/components/bs-modal/header.js
  addon/components/bs-modal/header/-close.js
  addon/components/bs-modal/header/-title.js
  addon/components/bs-modal/header/close.hbs
  addon/components/bs-modal/header/close.js
  addon/components/bs-modal/header/title.js
  addon/helpers/bs-noop.js
  app/helpers/bs-noop.js
  package.json
  tests/integration/components/bs-modal-simple-test.js
  tests/integration/components/subclassing-test.js
  yarn.lock
Labels: enhancement

#1382 Run ember-cli-update
  .eslintrc.js
  .github/workflows/ci.yml
  addon/components/bs-contextual-help.js
  config/ember-try.js
  package.json
  tests/dummy/app/app.js
  tests/dummy/app/router.js
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/targets.js
  tests/integration/components/bs-modal-simple-test.js
  tests/test-helper.js
  yarn.lock
Labels: internal

#1383 Fix cleanup of event listeners for Tooltips/Popovers
  addon/components/bs-contextual-help.js
Labels: bug
