Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2020-08, with the labels that each got.

#1183 Avoid using ref modifier in form
  addon/components/bs-form.js
  addon/templates/components/bs-form.hbs
Labels: bug

#1204 isSettled property of Button was documented as isFulfilled
  addon/components/bs-button.js
Labels: documentation

#1207 Fix CI config for running FastBoot tests
  .github/workflows/ci.yml
  config/ember-try.js
Labels: internal

#1203 yield setValue function from <form.element> to mutate the value in custom controls
  CHANGELOG.md
  addon/components/bs-form/element.js
  addon/templates/components/bs-form/element.hbs
  tests/integration/components/bs-form/element-test.js
Labels: enhancement

#1205 yield submitButton component from <BsForm>
  addon/components/bs-form.js
  addon/templates/components/bs-form.hbs
  tests/integration/components/bs-form-test.js
Labels: enhancement
