Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2020-01, with the labels that each got.

#951 support optional feature default-async-observers
  .travis.yml
  addon/components/base/bs-alert.js
  addon/components/base/bs-collapse.js
  addon/components/base/bs-form/element.js
  addon/components/base/bs-modal.js
  addon/components/base/bs-tab/pane.js
  config/ember-try.js
  tests/dummy/config/optional-features.json
Labels: bug

#948 Modals ignore clicking backdrop to close, if mousedown happened on dialog element, reflecting original bootstrap.js behaviour
  addon/components/base/bs-modal/dialog.js
  tests/integration/components/bs-modal-test.js
Labels: bug

#954 run lint and tests for docs app in CI
  .travis.yml
Labels: internal

#958 Fix missing "Addons" nav item in API docs
  docs/yuidoc-theme/layouts/main.handlebars
Labels: documentation

#959 Mention ember-angle-bracket-invocation-polyfill in setup guide
  docs/app/templates/getting-started/setup.hbs
Labels: documentation

#960 Add note to insertEmberWormholeElementToDom config when rendering app into custom element
  docs/app/templates/getting-started/setup.hbs
Labels: documentation

#964 upgrade ember to 3.15
  .npmignore
  .travis.yml
  config/ember-try.js
  package.json
  tests/dummy/app/app.js
  tests/dummy/app/resolver.js
  tests/dummy/app/templates/components/.gitkeep
  yarn.lock
Labels: internal

#965 drop support for ember < 3.15 and node 8
  .travis.yml
  README.md
  config/ember-try.js
  package.json
  yarn.lock
Labels: breaking

#970 add template linting for tests
  .eslintrc.js
  package.json
  tests/integration/components/bs-form/element-test.js
  tests/integration/components/bs-popover-test.js
  tests/integration/components/bs-tab-test.js
  tests/integration/components/bs-tooltip-test.js
  yarn.lock
Labels: internal

#932 radio group should have a legend not a label
  addon/components/bs4/bs-form/element.js
  addon/components/bs4/bs-form/element/label.js
  addon/components/bs4/bs-form/element/legend.js
  app/components/bs-form/element/legend.js
  tests/integration/components/bs-form/element-test.js
Labels: breaking, bug

#977 Move accordion/item/* templates to proper place
  addon/components/base/bs-accordion/item/body.js
  addon/components/base/bs-accordion/item/title.js
  addon/templates/components/bs3/bs-accordion/item/body.hbs
  addon/templates/components/bs3/bs-accordion/item/title.hbs
  addon/templates/components/bs4/bs-accordion/item/body.hbs
  addon/templates/components/bs4/bs-accordion/item/title.hbs
Labels: internal

#976 Convert `<BsAlert>` to tag-less / outerHTML component
  addon/components/base/bs-alert.js
  addon/components/bs3/bs-alert.js
  addon/components/bs4/bs-alert.js
  addon/templates/components/bs3/bs-alert.hbs
  addon/templates/components/bs4/bs-alert.hbs
  addon/templates/components/common/bs-alert.hbs
Labels: internal
