Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2020-09, with the labels that each got.

#1217 Fix CSP failures in FastBoot tests
  tests/dummy/config/content-security-policy.js
Labels: internal

#1218 Update docs for new yielded submit button
  docs/app/templates/demo/forms.hbs
  docs/package.json
  docs/yarn.lock
Labels: documentation

#1219 Fix Tooltips/Popovers when used w/ FastBoot and rehydration enabled
  addon/components/bs-contextual-help.js
Labels: bug

#1223 Manual include/exclude of components: <BsForm> requires <BsButton> due to yielded submitButton
  index.js
Labels: bug

#1225 Refactor BsCollapse to Glimmer component
  addon/components/bs-collapse.hbs
  addon/components/bs-collapse.js
Labels: enhancement

#1224 Refactor BsAlert to Glimmer component
  addon/components/bs-alert.hbs
  addon/components/bs-alert.js
  addon/utils/decorators/uses-transition.js
  package.json
  yarn.lock
Labels: enhancement

#1237 Deprecate @triggerElement="parentView" for Tooltips and Popovers
  addon/components/bs-contextual-help.js
  tests/integration/components/bs-tooltip-test.js
Labels: enhancement

#1249 upgrade @embroider/macros to fix usage in addons
  package.json
  yarn.lock
Labels: bug

#1250 <BsForm> should support @onBefore, @onSubmit and @onInvalid arguments to be undefined
  addon/components/bs-form.js
  tests/integration/components/bs-form-test.js
Labels: bug

#1257 fix usage example in accordion docs
  addon/components/bs-accordion.js
Labels: documentation

#1259 Support both ember-concurrency 1.x and 2.x
  .github/workflows/ci.yml
  config/ember-try.js
  package.json
  yarn.lock
Labels: enhancement

#1260 Declare _element property as private
  addon/components/bs-carousel/slide.js
  addon/components/bs-collapse.js
  addon/components/bs-dropdown/menu.js
  addon/components/bs-form/element.js
Labels: documentation

#1271 Add Embroider compatibility note
  README.md
Labels: documentation

#1272 Avoid deprecation warning for dropdown button
  addon/components/bs-dropdown/button.js
  tests/dummy/config/environment.js
  tests/helpers/setup-no-deprecations.js
Labels: bug
