Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2020-04, with the labels that each got.

#1029 Fix dropdown focus to stay on toggle element
  addon/components/base/bs-dropdown/menu.js
  addon/templates/components/bs3/bs-dropdown/menu.hbs
  addon/templates/components/bs4/bs-dropdown/menu.hbs
  tests/integration/components/bs-dropdown-test.js
Labels: bug

#1037 Drop support for Ember 3.15
  .travis.yml
  README.md
  config/ember-try.js
Labels: breaking

#1041 Fix autofocus for Modals in IE11
  addon/components/bs-modal/dialog.js
Labels: bug

#1040 setup release-it with lerna-changelog integration
  RELEASE.md
  gulpfile.js
  package.json
  yarn.lock
Labels: internal

#1043 Add Github Actions setup
  .github/workflows/ci.yml
  .travis.yml
Labels: internal

#1045 Add dependabot setup
  .dependabot/config.yml
Labels: internal

#1061 Fix first tab pane being active by default
  addon/components/bs-tab/pane.js
  tests/integration/components/bs-tab-test.js
Labels: bug
