Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2021-03, with the labels that each got.

#1441 upgrade ember-cli-htmlbars to v5.6.0
  package.json
  yarn.lock
Labels: dependencies

#1421 Do not use implicit this fallback in templates
  .template-lintrc.js
  addon/components/bs-accordion/item.hbs
  addon/components/bs-accordion/item.js
  addon/components/bs-dropdown.hbs
  addon/components/bs-modal/header.hbs
  addon/components/bs-popover.hbs
  addon/components/bs-tooltip.hbs
  tests/dummy/app/templates/acceptance/modal.hbs
  tests/integration/components/bs-accordion-test.js
  tests/integration/components/bs-alert-test.js
  tests/integration/components/bs-button-group-test.js
  tests/integration/components/bs-button-test.js
  tests/integration/components/bs-carousel-test.js
  tests/integration/components/bs-collapse-test.js
  tests/integration/components/bs-dropdown-test.js
  tests/integration/components/bs-form-test.js
  tests/integration/components/bs-form/element-test.js
  tests/integration/components/bs-form/element/errors-test.js
  tests/integration/components/bs-form/group-test.js
  tests/integration/components/bs-modal-simple-test.js
  tests/integration/components/bs-modal/footer-test.js
  tests/integration/components/bs-navbar-test.js
  tests/integration/components/bs-popover-test.js
  tests/integration/components/bs-progress-test.js
  tests/integration/components/bs-tab-test.js
  tests/integration/components/bs-tab/pane-test.js
  tests/integration/components/bs-tooltip-test.js
Labels: bug

#1448 Fix deprecations failing the build
  tests/helpers/setup-no-deprecations.js
  tests/integration/components/bs-dropdown-test.js
  tests/integration/components/bs-dropdown/menu-test.js
  tests/integration/components/bs-dropdown/menu/link-to-test.js
  tests/integration/components/bs-nav-test.js
  tests/integration/components/bs-nav/link-to-test.js
Labels: internal
