Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2021-08, with the labels that each got.

#1581 BsButton should not silenty catch errors thrown by @onClick handler
  addon/components/bs-button.js
  tests/helpers/assert-errors.js
  tests/integration/components/bs-button-test.js
  tests/integration/components/bs-form-test.js
Labels: bug

#1593 Drop support for ember-concurrency 1.x as a dependency
  .github/workflows/ci.yml
  config/ember-try.js
  package.json
  yarn.lock
Labels: breaking

#1595 Drop node 10 support
  .github/workflows/ci.yml
  README.md
  package.json
Labels: breaking

#1594 Fix tests for Ember 4.0 Canary
  package.json
  tests/helpers/setup-no-deprecations.js
  yarn.lock
Labels: internal

#1597 Add Bootstrap v5 support for Navbars
  addon/components/bs-navbar.hbs
  addon/components/bs-navbar.js
  tests/integration/components/bs-navbar-test.js
Labels: enhancement, Bootstrap 5

#1590 Fix `.collapsed` markup for accordions
  addon/components/bs-accordion/item/title.hbs
  tests/helpers/bootstrap.js
  tests/integration/components/bs-accordion-test.js
  tests/integration/components/bs-accordion/item-test.js
Labels: bug

#1537 Remove `.btn-block` support for Bootstrap 5
  addon/components/bs-button.hbs
  addon/components/bs-button.js
  tests/integration/components/bs-button-test.js
Labels: enhancement, Bootstrap 5

#1561 Add Bootstrap v5 support for accordions
  addon/components/bs-accordion/item.hbs
  addon/components/bs-accordion/item/body.hbs
  addon/components/bs-accordion/item/body.js
  addon/components/bs-accordion/item/title.hbs
  tests/helpers/bootstrap.js
Labels: enhancement, Bootstrap 5

#1603 Remove BS3 support from addon entrypoint
  index.js
Labels: breaking

#1604 Remove BS3 support from addon blueprint
  blueprints/ember-bootstrap/index.js
  node-tests/blueprints/dependencyScenarios.js
  node-tests/blueprints/ember-bootstrap-test.js
Labels: breaking
