Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2021-09, with the labels that each got.

#1608 Update dependencies for Ember 4 support
  package.json
  tests/integration/components/bs-form-test.js
  yarn.lock
Labels: enhancement

#1607 Permit blocking of dropdown close if onHide returns false
  addon/components/bs-dropdown.js
  tests/integration/components/bs-dropdown-test.js
Labels: enhancement

#1610 Remove deprecated `parentView` trigger element option for tooltips/popovers
  addon/components/bs-contextual-help.js
  addon/components/bs-popover.js
  addon/components/bs-tooltip.js
  addon/utils/dom.js
  docs/app/templates/demo/popover.hbs
  docs/app/templates/demo/tooltip.hbs
  tests/integration/components/bs-tooltip-test.js
Labels: breaking

#1609 Drop ember-popper in favor of ember-popper-modifier and popper.js v2
  addon/components/bs-contextual-help/element.js
  addon/components/bs-dropdown.hbs
  addon/components/bs-dropdown/menu.hbs
  addon/components/bs-dropdown/menu.js
  addon/components/bs-popover/element.hbs
  addon/components/bs-popover/element.js
  addon/components/bs-tooltip/element.hbs
  package.json
  tests/dummy/app/templates/fastboot/dropdown.hbs
  tests/helpers/contextual-help.js
  tests/integration/components/bs-popover-test.js
  tests/integration/components/bs-tooltip-test.js
  vendor/ember-bootstrap/bs4.css
  yarn.lock
Labels: enhancement, breaking

#1614 Fix BS5 markup for modal close button
  addon/components/bs-modal/header/close.hbs
  tests/acceptance/bs-modal-test.js
  tests/dummy/app/templates/fastboot/modal.hbs
  tests/helpers/bootstrap.js
  tests/integration/components/bs-modal-simple-test.js
  tests/integration/components/bs-modal/header-test.js
Labels: bug, Bootstrap 5

#1617 Add BS5 and remove remove BS3 instructions to docs app
  docs/app/controllers/getting-started/setup.js
  docs/app/router.js
  docs/app/templates/getting-started/assets.hbs
  docs/app/templates/getting-started/bootstrap-4.hbs
  docs/app/templates/getting-started/index.hbs
  docs/app/templates/getting-started/setup.hbs
Labels: documentation, Bootstrap 5

#1619 Add ember-bootstrap-postcss to addons section
  docs/app/templates/addons.hbs
Labels: documentation

#1620 Fix BS5 markup for alert close button
  addon/components/bs-alert.hbs
  tests/acceptance/bs-modal-test.js
  tests/helpers/bootstrap.js
  tests/integration/components/bs-alert-test.js
  tests/integration/components/bs-modal-simple-test.js
  tests/integration/components/bs-modal/header-test.js
Labels: bug, Bootstrap 5
