Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2021-05, with the labels that each got.

#1496 Support Bootstrap v5 in addon index.js
  index.js
  package.json
  yarn.lock
Labels: Bootstrap 5, enhancement

#1497 Support Bootstrap5 in default blueprint
  .eslintrc.js
  blueprints/.eslintrc.js
  blueprints/ember-bootstrap/index.js
  node-tests/.eslintrc.js
  node-tests/blueprints/dependencyScenarios.js
  node-tests/blueprints/ember-bootstrap-test.js
  node-tests/index-tests.js
Labels: Bootstrap 5, enhancement

#1499 Add experimental/incomplete Bootstrap 5 support to existing components
  .github/workflows/ci.yml
  addon/components/bs-accordion.hbs
  addon/components/bs-accordion/item.hbs
  addon/components/bs-accordion/item.js
  addon/components/bs-accordion/item/body.hbs
  addon/components/bs-accordion/item/title.hbs
  addon/components/bs-alert.hbs
  addon/components/bs-carousel.hbs
  addon/components/bs-carousel/slide.hbs
  addon/components/bs-collapse.hbs
  addon/components/bs-dropdown.hbs
  addon/components/bs-dropdown/menu.hbs
  addon/components/bs-dropdown/menu/divider.hbs
  addon/components/bs-dropdown/menu/link-to.js
  addon/components/bs-dropdown/toggle.hbs
  addon/components/bs-form/element.hbs
  addon/components/bs-form/element/control/checkbox.hbs
  addon/components/bs-form/element/control/input.hbs
  addon/components/bs-form/element/control/textarea.hbs
  addon/components/bs-form/group.hbs
  addon/components/bs-modal.hbs
  addon/components/bs-modal/dialog.hbs
  addon/components/bs-modal/header.hbs
  addon/components/bs-modal/header/title.hbs
  addon/components/bs-nav.hbs
  addon/components/bs-nav/item.hbs
  addon/components/bs-nav/link-to.js
  addon/components/bs-navbar.hbs
  addon/components/bs-navbar.js
  addon/components/bs-navbar/toggle.hbs
  addon/components/bs-popover/element.hbs
  addon/components/bs-progress/bar.hbs
  addon/components/bs-progress/bar.js
  addon/components/bs-tab/pane.hbs
  addon/components/bs-tooltip/element.hbs
  config/ember-try.js
  index.js
  tests/helpers/bootstrap.js
  tests/integration/components/bs-accordion-test.js
  tests/integration/components/bs-button-test.js
  tests/integration/components/bs-carousel-test.js
  tests/integration/components/bs-dropdown-test.js
  tests/integration/components/bs-dropdown/menu-test.js
  tests/integration/components/bs-dropdown/menu/divider-test.js
  tests/integration/components/bs-dropdown/menu/item-test.js
  tests/integration/components/bs-dropdown/menu/link-to-test.js
  tests/integration/components/bs-form-test.js
  tests/integration/components/bs-form/element-test.js
  tests/integration/components/bs-form/element/control/checkbox-test.js
  tests/integration/components/bs-form/element/control/input-test.js
  tests/integration/components/bs-form/element/label-test.js
  tests/integration/components/bs-form/group-test.js
  tests/integration/components/bs-modal-simple-test.js
  tests/integration/components/bs-nav-test.js
  tests/integration/components/bs-nav/link-to-test.js
  tests/integration/components/bs-navbar-test.js
  tests/integration/components/bs-navbar/toggle-test.js
  tests/integration/components/bs-popover-test.js
  tests/integration/components/bs-progress-test.js
  tests/integration/components/bs-tooltip-test.js
Labels: Bootstrap 5, enhancement

#1495 Support switch control in forms (BS4 only)
  addon/components/bs-form/element.hbs
  addon/components/bs-form/element.js
  addon/components/bs-form/element/control/switch.hbs
  addon/components/bs-form/element/control/switch.js
  addon/components/bs-form/element/label.hbs
  addon/components/bs-form/element/layout/horizontal/checkbox.hbs
  addon/components/bs-form/element/layout/inline/checkbox.hbs
  addon/components/bs-form/element/layout/vertical/checkbox.hbs
  app/components/bs-form/element/control/switch.js
  docs/app/controllers/demo/forms.js
  docs/app/templates/demo/forms.hbs
  tests/integration/components/bs-form/element-test.js
  tests/integration/components/bs-form/element/control/switch-test.js
  tests/integration/components/bs-form/element/label-test.js
Labels: Bootstrap 4, enhancement

#1455 Refactor Nav/Navbar/Dropdown's LinkTo components to not extend from Ember's LinkComponent
  addon/components/bs-dropdown/menu.hbs
  addon/components/bs-dropdown/menu/link-to.js
  addon/components/bs-link-to.hbs
  addon/components/bs-link-to.js
  addon/components/bs-nav.hbs
  addon/components/bs-nav/item.js
  addon/components/bs-nav/link-to.js
  addon/components/bs-navbar/link-to.hbs
  addon/components/bs-navbar/link-to.js
  app/components/bs-dropdown/menu/link-to.js
  app/components/bs-link-to.js
  app/components/bs-nav/link-to.js
  tests/acceptance/bs-nav-link-test.js
  tests/helpers/setup-no-deprecations.js
  tests/integration/components/bs-dropdown/menu/link-to-test.js
  tests/integration/components/bs-nav-test.js
  tests/integration/components/bs-nav/item-test.js
  tests/integration/components/bs-nav/link-to-test.js
Labels: enhancement

#1510 Fix CI for running Firefox
  .github/workflows/ci.yml
Labels: internal

#1502 Update Tooltips and Popovers for Bootstrap 5
  addon/components/bs-contextual-help/element.js
  addon/components/bs-popover/element.hbs
  addon/components/bs-popover/element.js
  addon/components/bs-tooltip/element.hbs
  addon/components/bs-tooltip/element.js
  tests/helpers/bootstrap.js
  tests/helpers/contextual-help.js
  tests/integration/components/bs-popover-test.js
  tests/integration/components/bs-tooltip-test.js
Labels: Bootstrap 5, enhancement

#1504 Deprecate positional arguments for link-to components
  addon/components/bs-link-to.js
  tests/helpers/setup-no-deprecations.js
  tests/integration/components/bs-dropdown/menu/link-to-test.js
  tests/integration/components/bs-nav/link-to-test.js
Labels: enhancement

#1516 Fix horizontal form layout for checkbox elements
  addon/components/bs-form/element/layout/horizontal/checkbox.js
  tests/integration/components/bs-form/element-test.js
Labels: bug

#1500 Re-add broken fade arg to BsAlert component
  addon/components/bs-alert.js
Labels: bug

#1513 forward arguments in <BsNavbar::LinkTo> to <BsLinkTo>
  addon/components/bs-navbar/link-to.hbs
  tests/integration/components/bs-navbar-test.js
Labels: bug

#1512 Update forms for Bootstrap 5
  addon/components/bs-form.js
  addon/components/bs-form/element.hbs
  addon/components/bs-form/element/control/switch.hbs
  addon/components/bs-form/element/label.hbs
  addon/components/bs-form/element/layout/horizontal/checkbox.hbs
  addon/components/bs-form/element/layout/inline/checkbox.hbs
  addon/components/bs-form/element/layout/vertical/checkbox.hbs
  addon/components/bs-form/group.hbs
  index.js
  tests/fastboot/form-test.js
  tests/helpers/bootstrap.js
  tests/integration/components/bs-form-test.js
  tests/integration/components/bs-form/element-test.js
  tests/integration/components/bs-form/element/control/switch-test.js
  tests/integration/components/bs-form/element/label-test.js
  tests/integration/components/bs-form/group-test.js
Labels: Bootstrap 5, enhancement

#1517 Fixed component dependencies when using `whitelist` to "tree-shake" components
  index.js
Labels: bug

#1519 Fix Navbar link markup regression introduced in v4.7.0
  addon/components/bs-navbar.hbs
  addon/components/bs-navbar/link-to.hbs
  tests/integration/components/bs-navbar/nav-test.js
Labels: bug

#1466 Add test coverage for modal animation
  tests/integration/components/bs-modal-test.js
Labels: internal

#1528 refactor to async/await instead of callbacks in BsModal
  addon/components/bs-modal.js
Labels: internal

#1527 register resize listener using on-window helper in BsModal
  addon/components/bs-modal.hbs
  addon/components/bs-modal.js
Labels: internal

#1529 Shadow DOM compatibility
  addon/components/bs-contextual-help.js
  addon/components/bs-contextual-help/element.js
  addon/components/bs-modal.hbs
  addon/components/bs-modal.js
  addon/components/bs-popover.hbs
  addon/components/bs-popover/element.hbs
  addon/components/bs-tooltip.hbs
  addon/components/bs-tooltip/element.hbs
  addon/utils/dom.js
Labels: enhancement

#1531 refactor handleBackdrop method of <BsModal> into separate show and hide methods
  addon/components/bs-modal.hbs
  addon/components/bs-modal.js
  tests/integration/components/bs-modal-test.js
Labels: internal

#1534 Update ember-focus-trap
  addon/components/bs-modal/dialog.hbs
  package.json
  tests/helpers/setup-no-deprecations.js
  yarn.lock
Labels: internal

#1538 Fix BsButtonGroup radio to not trigger onChange when clicking active button
  addon/components/bs-button-group.js
  tests/integration/components/bs-button-group-test.js
Labels: bug

#1541 Change `.sr-only` utility to `.visually-hidden` for Bootstrap v5
  addon/components/bs-carousel.hbs
  addon/components/bs-form/element/label.hbs
  addon/components/bs-form/element/legend.hbs
  addon/components/bs-navbar/toggle.hbs
  addon/components/bs-progress/bar.hbs
  tests/helpers/bootstrap.js
  tests/integration/components/bs-carousel-test.js
  tests/integration/components/bs-form/element-test.js
  tests/integration/components/bs-progress-test.js
Labels: Bootstrap 5, enhancement

#1533 harmonize code paths used in FastBoot and non-FastBoot of <BsModal>
  addon/components/bs-modal.js
Labels: internal

#1226 Refactor BsAccordion to Glimmer component
  addon/components/bs-accordion.js
  addon/components/bs-accordion/item.hbs
  addon/components/bs-accordion/item.js
  addon/components/bs-accordion/item/_body.js
  addon/components/bs-accordion/item/body.js
  addon/components/bs-accordion/item/title.hbs
  addon/components/bs-accordion/item/title.js
  package.json
  yarn.lock
Labels: enhancement
