Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2021-11, with the labels that each got.

#1689 Make Bootstrap 5 the new default when adding the addon
  blueprints/ember-bootstrap/index.js
  config/ember-try.js
  index.js
  node-tests/blueprints/dependencyScenarios.js
  package.json
  tests/dummy/config/environment.js
  yarn.lock
Labels: enhancement

#1699 modal footer should not render a <form> element
  addon/components/bs-modal/footer.hbs
Labels: breaking

#1706 Remove use of curly component invocation for link components
  tests/integration/components/bs-dropdown/menu/link-to-test.js
  tests/integration/components/bs-nav/link-to-test.js
Labels: internal
