Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2022-02, with the labels that each got.

#1747 Update ember-element-helper
  package.json
  yarn.lock
Labels: dependencies

#1750 Needs peerDependency on ember-source
  package.json
Labels: bug

#1758 drop private @class argument of <BsDropdown::Menu>
  addon/components/bs-dropdown/menu.hbs
Labels: internal

#1755 drop private @class argument of <BsModal>
  addon/components/bs-modal.hbs
  tests/integration/components/bs-modal-test.js
Labels: internal

#1759 drop @class argument of <BsTooltip> and <BsTooltip::Element>
  addon/components/bs-tooltip.hbs
  addon/components/bs-tooltip/element.hbs
  tests/integration/components/bs-tooltip-test.js
Labels: internal

#1757 pass class as attribute to <BsLinkTo> if possible
  addon/components/bs-navbar/link-to.hbs
Labels: internal

#1760 drop @class argument of <BsPopover> and <BsPopover::Element>
  addon/components/bs-popover.hbs
  addon/components/bs-popover/element.hbs
  tests/integration/components/bs-popover-test.js
Labels: internal

#1762 Update ember-cli-fastboot
  docs/package.json
  package.json
  yarn.lock
Labels: dependencies
