Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2022-05, with the labels that each got.

#1790 Bug fix: carousel component missing from API docs
  addon/components/bs-carousel.js
Labels: documentation

#1787 Added missing tests for assertion of href attribute for BsNavbar
  tests/acceptance/bs-nav-link-test.js
  tests/integration/components/bs-navbar/nav-test.js
Labels: internal

#1791 Fix typos in API docs
  addon/components/bs-alert.js
  addon/components/bs-button.js
  addon/components/bs-carousel.js
  addon/components/bs-dropdown.js
  addon/components/bs-form.js
  addon/components/bs-form/element.js
  addon/components/bs-modal-simple.js
  addon/components/bs-modal.js
  addon/components/bs-popover.js
  addon/components/bs-progress.js
  addon/components/bs-tooltip.js
Labels: documentation

#1793 Add form element to arguments passed to validate hook
  addon/components/bs-form.hbs
  addon/components/bs-form.js
  tests/integration/components/bs-form-test.js
Labels: enhancement
