Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2022-03, with the labels that each got.

#1741 Implement fullscreen modal with BS breakpoints
  addon/components/bs-modal.hbs
  addon/components/bs-modal.js
  addon/components/bs-modal/dialog.hbs
  tests/integration/components/bs-modal-test.js
Labels: enhancement, Bootstrap 5

#1768 Fix broken aria-labelledby attribute of modals
  addon/components/bs-modal/dialog.js
  tests/integration/components/bs-modal-simple-test.js
Labels: bug

#1769 Fix a11y markup of Tabs
  addon/components/bs-tab.hbs
  tests/integration/components/bs-tab-test.js
Labels: bug, a11y

#1770 Fix markup of tabs with dropdowns
  addon/components/bs-tab.hbs
  tests/integration/components/bs-tab-test.js
Labels: bug

#1771 Document a11y markup for progress bar
  addon/components/bs-progress.js
  tests/integration/components/bs-progress-test.js
Labels: documentation

#1772 Convert form controls to Glimmer components
  addon/components/bs-form/element/control.js
  addon/components/bs-form/element/control/checkbox.hbs
  addon/components/bs-form/element/control/checkbox.js
  addon/components/bs-form/element/control/input.hbs
  addon/components/bs-form/element/control/input.js
  addon/components/bs-form/element/control/radio.hbs
  addon/components/bs-form/element/control/radio.js
  addon/components/bs-form/element/control/switch.hbs
  addon/components/bs-form/element/control/switch.js
  addon/components/bs-form/element/control/textarea.hbs
  addon/components/bs-form/element/control/textarea.js
  addon/utils/cp/form-validation-class.js
  addon/utils/form-validation-class.js
  addon/utils/size-class.js
Labels: enhancement

#1774 Convert remaining form components to TO/Glimmer
  addon/components/bs-form/element/errors.hbs
  addon/components/bs-form/element/errors.js
  addon/components/bs-form/element/feedback-icon.hbs
  addon/components/bs-form/element/feedback-icon.js
  addon/components/bs-form/element/help-text.js
  addon/components/bs-form/element/label.hbs
  addon/components/bs-form/element/label.js
  addon/components/bs-form/element/legend.hbs
  addon/components/bs-form/element/legend.js
Labels: enhancement
