Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2023-01, with the labels that each got.

#1838 drop support for node 12 and 17
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  README.md
  docs/package.json
  package.json
Labels: breaking

#1839 drop support for Ember 3.24
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
  package.json
Labels: breaking

#1844 fix HTML markup for <BsAccordion> per Bootstrap docs
  addon/components/bs-accordion.hbs
  addon/components/bs-accordion/item.hbs
  addon/components/bs-accordion/item/body.hbs
  addon/components/bs-accordion/item/title.hbs
  package.json
  tests/helpers/bootstrap.js
  tests/integration/components/bs-accordion-test.js
  yarn.lock
Labels: breaking

#1849 drop dependency on @ember/string
  addon/components/bs-collapse.js
  tests/helpers/setup-no-deprecations.js
Labels: enhancement

#1851 ignore docs/build generated by docs build in ESLint
  docs/.eslintignore
Labels: internal

#1850 run lint and tests for docs app in CI
  .github/workflows/ci.yml
  docs/app/controllers/demo/list-group.js
  docs/app/controllers/demo/modal.js
  docs/app/routes/demo/list-group.js
  docs/tests/unit/routes/demo/list-group-test.js
Labels: internal

#1812 control programmatically if validation errors should be shown
  addon/components/bs-form.js
  tests/integration/components/bs-form-test.js
Labels: enhancement

#1841 support ember-ref-bucket v5
  package.json
  yarn.lock
Labels: enhancement

#1852 support ember-popper-modifier v3
  package.json
  yarn.lock
Labels: enhancement

#1853 use ember-modifier v4
  package.json
  yarn.lock
Labels: enhancement

#1854 Drop polyfills not needed anymore
  package.json
  yarn.lock
Labels: enhancement

#1856 polyfill for unique-id helper is required to support Ember < 4.4
  package.json
Labels: bug
