Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2023-03, with the labels that each got.

#1874 remove usage of outdated component name at demo page for BsDropdown
  docs/app/templates/demo/dropdown.hbs
Labels: documentation

#1870 move @glimmer/component and @glimmer/tracking to peer dependencies
  package.json
Labels: breaking

#1867 fix: correct dropdown direction class for BS5
  addon/components/bs-dropdown.js
  tests/integration/components/bs-dropdown-test.js
Labels: bug

#1879 run tests against all supported Ember LTS versions in CI
  .github/workflows/ci.yml
  config/ember-try.js
Labels: internal

#1878 add basic test coverage for docs app
  docs/app/templates/demo/carousel.hbs
  docs/package.json
  docs/tests/acceptance/addons-test.js
  docs/tests/acceptance/components-test.js
  docs/tests/acceptance/components/accordion-test.js
  docs/tests/acceptance/components/alert-test.js
  docs/tests/acceptance/components/button-group-test.js
  docs/tests/acceptance/components/button-test.js
  docs/tests/acceptance/components/carousel-test.js
  docs/tests/acceptance/components/collapse-test.js
  docs/tests/acceptance/components/dropdown-test.js
  docs/tests/acceptance/components/forms-test.js
  docs/tests/acceptance/components/list-group-test.js
  docs/tests/acceptance/components/modal-test.js
  docs/tests/acceptance/components/navbars-test.js
  docs/tests/acceptance/components/navs-test.js
  docs/tests/acceptance/components/popover-test.js
  docs/tests/acceptance/components/progress-test.js
  docs/tests/acceptance/components/spinner-test.js
  docs/tests/acceptance/components/tabs-test.js
  docs/tests/acceptance/components/tooltip-test.js
  docs/tests/acceptance/getting-started-test.js
  docs/tests/acceptance/getting-started/assets-test.js
  docs/tests/acceptance/getting-started/setup-test.js
  docs/tests/acceptance/index-test.js
  docs/tests/test-helper.js
  docs/yarn.lock
Labels: internal

#1895 support tracked-toolbox v2
  .github/workflows/ci.yml
  config/ember-try.js
  package.json
  yarn.lock
Labels: enhancement

#1901 should not run ember test for node-tests scenario
  .github/workflows/ci.yml
  config/ember-try.js
Labels: internal

#1908 remove ember-export-application-global dev dependency
  docs/package.json
  package.json
  yarn.lock
Labels: internal

#1909 Disable fastboot tests for ember canary
  config/ember-try.js
Labels: internal

#1811 Yield form's model from <BsForm>
  addon/components/bs-form.hbs
  addon/components/bs-form.js
  tests/integration/components/bs-form-test.js
Labels: enhancement

#1911 Fix submitOnEnter when multiple input elements are present
  addon/components/bs-form.js
  tests/integration/components/bs-form-test.js
Labels: bug

#1913 remove buttonType argument of <BsButton>
  addon/components/bs-button.hbs
  addon/components/bs-button.js
  addon/components/bs-form.hbs
  tests/integration/components/bs-button-test.js
  tests/integration/components/bs-form-test.js
Labels: breaking
