Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2023-12, with the labels that each got.

#2034 Update bs-tab and related components to Glimmer component
  addon/components/bs-tab.hbs
  addon/components/bs-tab.js
  addon/components/bs-tab/pane.hbs
  addon/components/bs-tab/pane.js
Labels: enhancement

#2038 Update bs-carousel and related components to Glimmer components
  addon/components/bs-carousel.hbs
  addon/components/bs-carousel.js
  addon/components/bs-carousel/slide.hbs
  addon/components/bs-carousel/slide.js
  tests/integration/components/bs-carousel-test.js
Labels: enhancement

#2040 Drop active and disabled classes from . nav-item only expected for BS3
  addon/components/bs-link-to.js
  addon/components/bs-nav/item.hbs
  addon/components/bs-nav/item.js
  tests/acceptance/bs-nav-link-test.js
  tests/fastboot/tab-test.js
  tests/integration/components/bs-nav/item-test.js
  tests/integration/components/bs-tab-test.js
Labels: bug

#2042 refactor from computed property to glimmer tracking caching
  addon/components/bs-modal.js
Labels: internal

#2044 remove unused computed property utils
  addon/utils/cp/listen-to.js
  addon/utils/cp/overrideable.js
  addon/utils/cp/size-class.js
  addon/utils/cp/uses-transition.js
Labels: internal

#2046 refactor @defaultValue decorator to plain getter
  addon/components/bs-navbar/nav.js
  addon/utils/default-decorator.js
Labels: invalid

#2047 remove unused mixins for component parent <-> child relationship
  addon/mixins/component-child.js
  addon/mixins/component-parent.js
Labels: internal

#2041 Run tests on Safari in CI (again)
  .github/workflows/ci.yml
  package.json
  pnpm-lock.yaml
  testem.browserstack.js
  testem.safari.js
Labels: internal

#2048 Add bs-collapse to the include list of bs-navbar
  index.js
Labels: bug

#2050 Remove browserstack from README.md
  README.md
  docs/Browserstack-logo.svg
Labels: documentation

#2049 Drop component subclassing deprecation
  addon/components/bs-accordion.js
  addon/components/bs-accordion/item.js
  addon/components/bs-accordion/item/title.js
  addon/components/bs-alert.js
  addon/components/bs-button-group.js
  addon/components/bs-button-group/button.js
  addon/components/bs-button.js
  addon/components/bs-carousel.js
  addon/components/bs-carousel/slide.js
  addon/components/bs-collapse.js
  addon/components/bs-dropdown.js
  addon/components/bs-dropdown/button.js
  addon/components/bs-dropdown/menu.js
  addon/components/bs-dropdown/menu/divider.js
  addon/components/bs-dropdown/menu/item.js
  addon/components/bs-dropdown/toggle.js
  addon/components/bs-form.js
  addon/components/bs-form/element/control/checkbox.js
  addon/components/bs-form/element/control/input.js
  addon/components/bs-form/element/control/radio.js
  addon/components/bs-form/element/control/switch.js
  addon/components/bs-form/element/control/textarea.js
  addon/components/bs-form/element/label.js
  addon/components/bs-form/element/legend.js
  addon/components/bs-modal.js
  addon/components/bs-modal/dialog.js
  addon/components/bs-nav.js
  addon/components/bs-nav/item.js
  addon/components/bs-navbar.js
  addon/components/bs-navbar/content.js
  addon/components/bs-navbar/nav.js
  addon/components/bs-navbar/toggle.js
  addon/components/bs-popover.js
  addon/components/bs-progress.js
  addon/components/bs-progress/bar.js
  addon/components/bs-tab.js
  addon/components/bs-tab/pane.js
  addon/components/bs-tooltip.js
  addon/utils/deprecate-subclassing.js
  tests/integration/components/subclassing-test.js
Labels: enhancement

#2052 remove unused dependency on ember-decorators
  package.json
  pnpm-lock.yaml
Labels: enhancement

#2054 Use @cached decorator from @glimmer/tracking rather than 3rd party library
  addon/components/bs-form.js
Labels: internal
