Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2023-11, with the labels that each got.

#1956 fix failing tests in CI due to change in recent Bootstrap version
  package.json
  tests/integration/components/bs-tooltip-test.js
  yarn.lock
Labels: internal

#1952 support ember-concurrency v3
  package.json
  yarn.lock
Labels: enhancement

#1935 Replace blacklist/whitelist with include/exclude in config (fixes #1154)
  .prettierignore
  docs/app/templates/getting-started/setup.hbs
  index.js
  node-tests/index-tests.js
Labels: breaking

#1961 drop support for node 16
  .github/workflows/ci.yml
  README.md
  package.json
Labels: breaking

#1962 clean-up leftovers from removed @buttonType argument of BsButton
  addon/components/bs-button-group/button.hbs
  addon/components/bs-dropdown/button.hbs
  addon/components/bs-form.js
  addon/components/bs-form/element.js
  tests/dummy/app/templates/fastboot/forms.hbs
Labels: documentation

#1958 support ember-popper-modifier v4
  config/ember-try.js
  package.json
  yarn.lock
Labels: enhancement

#1950 Support ember-element-helper v0.7.0 and v0.8.0
  package.json
  yarn.lock
Labels: enhancement

#1996 drop support for Ember < 4.8
  .github/workflows/ci.yml
  README.md
  config/ember-try.js
  package.json
Labels: breaking

#2001 improve wording of error message for removed whitelist / blacklist option
  index.js
  node-tests/index-tests.js
Labels: enhancement

#2008 drop support for Ember classic (optional features)
  .github/workflows/ci.yml
  config/ember-try.js
Labels: breaking

#2009 upgrade docs app with Ember CLI 4.12 blueprints
  docs/.ember-cli
  docs/.eslintignore
  docs/.eslintrc.js
  docs/.github/workflows/ci.yml
  docs/.gitignore
  docs/.prettierignore
  docs/.stylelintignore
  docs/.stylelintrc.js
  docs/README.md
  docs/app/index.html
  docs/app/styles/app.scss
  docs/app/styles/bs-example.scss
  docs/app/styles/highlight.scss
  docs/app/styles/variables.scss
  docs/app/templates/demo/modal.hbs
  docs/config/ember-cli-update.json
  docs/config/environment.js
  docs/ember-cli-build.js
  docs/package.json
  docs/tests/helpers/.gitkeep
  docs/tests/helpers/index.js
  docs/tests/index.html
  docs/yarn.lock
Labels: internal

#2010 upgrade addon with Ember CLI v4.12 blueprints
  .ember-cli
  .eslintrc.js
  .gitignore
  .npmignore
  .stylelintignore
  .stylelintrc.js
  CONTRIBUTING.md
  README.md
  config/environment.js
  ember-cli-build.js
  package.json
  tests/dummy/app/index.html
  tests/dummy/app/styles/app.css
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/dummy/config/environment.js
  tests/helpers/.gitkeep
  tests/helpers/index.js
  tests/index.html
  yarn.lock
Labels: internal

#2011 ember-unique-id-helper-polyfill is not needed anymove
  package.json
  yarn.lock
Labels: enhancement

#2015 migrate to actievely maintained lerna-changelog release-it plugin
  package.json
  yarn.lock
Labels: internal

#2016 Fix outdated repository URLs in package.json
  package.json
Labels: documentation

#2017 Drop dependency resolution overwrite not needed anymore
  package.json
Labels: internal

#2018 fix broken readme due to merge conflicts
  README.md
Labels: documentation

#2020 Refactor BsNav to Glimmer component
  addon/components/bs-nav.js
Labels: enhancement

#2025 Refactor BsNavbar, BsNavbar::Content and BSNavbar::Toggle to Glimmer components
  addon/components/bs-navbar.hbs
  addon/components/bs-navbar.js
  addon/components/bs-navbar/content.js
  addon/components/bs-navbar/toggle.hbs
  addon/components/bs-navbar/toggle.js
Labels: enhancement

#2027 Refactor bs-alert to remove @localCopy and avoid mutation after consumption error in Ember canary
  addon/components/bs-alert.hbs
  addon/components/bs-alert.js
  tests/integration/components/bs-alert-test.js
Labels: bug

#2028 #1979 Migrate project to pnpm
  .github/workflows/ci.yml
  .github/workflows/docs.yml
  .gitignore
  config/ember-try.js
  docs/.github/workflows/ci.yml
  docs/config/ember-cli-update.json
  docs/package.json
  docs/pnpm-lock.yaml
  docs/yarn.lock
  package.json
  pnpm-lock.yaml
  renovate.json
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  yarn.lock
Labels: internal

#2031 Update bs-dropdown and related components to Glimmer component
  addon/components/bs-dropdown.hbs
  addon/components/bs-dropdown.js
  addon/components/bs-dropdown/menu.hbs
  addon/components/bs-dropdown/menu.js
  addon/components/bs-dropdown/menu/divider.js
  addon/components/bs-dropdown/menu/item.js
  addon/components/bs-dropdown/toggle.js
Labels: enhancement

#1946 bs-dropdown dynamic positioning should not be used when in a navbar
  addon/components/bs-dropdown.hbs
  addon/components/bs-dropdown/menu.js
  tests/integration/components/bs-dropdown-test.js
  tests/integration/components/bs-nav-test.js
Labels: bug
