Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2024-08, with the labels that each got.

#2107 Support ember-concurrency v4
  ember-bootstrap/addon/components/bs-carousel.js
  ember-bootstrap/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: enhancement, breaking

#2146 Tests: Remove action helper from bs-dropdown tests and convert to gjs
  test-app/tests/integration/components/bs-dropdown-test.gjs
  test-app/tests/integration/components/bs-dropdown/toggle-test.gjs
Labels: internal

#2147 Tests: Remove action helper from bs-modal tests and convert to gjs
  test-app/tests/integration/components/bs-modal-simple-test.gjs
  test-app/tests/integration/components/bs-modal-test.gjs
Labels: internal

#2143 Run tests for fastboot with ember-canary and Embroider
  test-app/config/ember-try.js
  test-app/ember-cli-build.js
Labels: internal

#2148 Tests: Remove action helper from bs-form tests and convert to gjs
  test-app/tests/integration/components/bs-form-test.gjs
  test-app/tests/integration/components/bs-form/element-test.gjs
Labels: internal

#2149 Tests: Remove action helper from bs-navbar and bs-nav tests and convert to gjs
  test-app/tests/integration/components/bs-nav/item-test.gjs
  test-app/tests/integration/components/bs-navbar-test.gjs
Labels: internal

#2150 Tests: Remove remaining action helpers from tests and convert to gjs
  test-app/tests/integration/components/bs-accordion/item-test.gjs
  test-app/tests/integration/components/bs-alert-test.gjs
  test-app/tests/integration/components/bs-popover-test.gjs
  test-app/tests/integration/components/bs-tab-test.gjs
  test-app/tests/integration/components/bs-tooltip-test.gjs
Labels: internal

#2152 Replace {{action}} helper in doc comments with modern patterns
  ember-bootstrap/addon/components/bs-button-group.js
  ember-bootstrap/addon/components/bs-dropdown.js
  ember-bootstrap/addon/components/bs-form.js
  ember-bootstrap/addon/components/bs-form/element.js
  ember-bootstrap/addon/components/bs-modal.js
  ember-bootstrap/addon/components/bs-navbar.js
  ember-bootstrap/addon/components/bs-popover.js
  ember-bootstrap/addon/components/bs-tab.js
  ember-bootstrap/addon/components/bs-tooltip.js
Labels: documentation

#2151 Tests: Re-enable template-lint rules and fix remaining issues
  test-app/.template-lintrc.js
  test-app/tests/helpers/setup-no-deprecations.ts
  test-app/tests/integration/components/bs-dropdown-test.gjs
  test-app/tests/integration/components/bs-form-test.gjs
  test-app/tests/integration/components/bs-list-group-test.js
  test-app/tests/integration/components/bs-list-group/item-test.js
  test-app/tests/integration/components/bs-modal-simple-test.gjs
  test-app/tests/integration/components/bs-popover-test.gjs
  test-app/tests/integration/components/bs-tooltip-test.gjs
Labels: internal
