Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2024-04, with the labels that each got.

#2119 Fix tooltip offset when using Bootstrap > 5.3
  ember-bootstrap/addon/components/bs-tooltip/element.js
  test-app/tests/integration/components/bs-tooltip-test.js
Labels: bug

#2120 Fix alignment of dropdown menus when using Bootstrap 5
  ember-bootstrap/addon/components/bs-dropdown/menu.hbs
  ember-bootstrap/addon/components/bs-dropdown/menu.js
  test-app/tests/integration/components/bs-dropdown/menu-test.js
Labels: bug

#2114 Refactor tests for dropdown menu
  test-app/tests/integration/components/bs-dropdown/menu-test.js
Labels: internal

#2122 modernize hbs import in tests
  test-app/tests/integration/components/bs-accordion-test.js
  test-app/tests/integration/components/bs-accordion/item-test.js
  test-app/tests/integration/components/bs-alert-test.js
  test-app/tests/integration/components/bs-button-group-test.js
  test-app/tests/integration/components/bs-carousel-test.js
  test-app/tests/integration/components/bs-dropdown-test.js
  test-app/tests/integration/components/bs-dropdown/button-test.js
  test-app/tests/integration/components/bs-dropdown/menu-test.js
  test-app/tests/integration/components/bs-dropdown/menu/divider-test.js
  test-app/tests/integration/components/bs-dropdown/menu/item-test.js
  test-app/tests/integration/components/bs-dropdown/menu/link-to-test.js
  test-app/tests/integration/components/bs-dropdown/toggle-test.js
  test-app/tests/integration/components/bs-form-test.js
  test-app/tests/integration/components/bs-form/element-test.js
  test-app/tests/integration/components/bs-form/element/control/checkbox-test.js
  test-app/tests/integration/components/bs-form/element/control/input-test.js
  test-app/tests/integration/components/bs-form/element/control/switch-test.js
  test-app/tests/integration/components/bs-form/element/control/textarea-test.js
  test-app/tests/integration/components/bs-form/element/errors-test.js
  test-app/tests/integration/components/bs-form/element/feedback-icon-test.js
  test-app/tests/integration/components/bs-form/element/help-text-test.js
  test-app/tests/integration/components/bs-form/element/label-test.js
  test-app/tests/integration/components/bs-modal-simple-test.js
  test-app/tests/integration/components/bs-modal-test.js
  test-app/tests/integration/components/bs-modal/footer-test.js
  test-app/tests/integration/components/bs-modal/header-test.js
  test-app/tests/integration/components/bs-nav-test.js
  test-app/tests/integration/components/bs-nav/item-test.js
  test-app/tests/integration/components/bs-nav/link-to-test.js
  test-app/tests/integration/components/bs-navbar-test.js
  test-app/tests/integration/components/bs-navbar/content-test.js
  test-app/tests/integration/components/bs-navbar/nav-test.js
  test-app/tests/integration/components/bs-navbar/toggle-test.js
  test-app/tests/integration/components/bs-popover-test.js
  test-app/tests/integration/components/bs-progress-test.js
  test-app/tests/integration/components/bs-tab-test.js
  test-app/tests/integration/components/bs-tab/pane-test.js
  test-app/tests/integration/components/bs-tooltip-test.js
Labels: internal

#2110 Dropdown should not add .btn-group class
  ember-bootstrap/addon/components/bs-dropdown.js
  test-app/tests/integration/components/bs-dropdown-test.js
Labels: bug

#2123 Add @ to `onClick` in BsModal::Footer submit button
  ember-bootstrap/addon/components/bs-modal/footer.hbs
  ember-bootstrap/addon/modifiers/bs-conditional-attribute.ts
  ember-bootstrap/app/modifiers/bs-conditional-attribute.js
  ember-bootstrap/package.json
  ember-bootstrap/types/glint.d.ts
  pnpm-lock.yaml
  test-app/tests/integration/components/bs-modal/footer-test.js
  test-app/tests/integration/modifiers/bs-conditional-attribute-test.ts
  test-app/types/glint.d.ts
Labels: bug

#2111 Extend `<BsButton>` component by invoking it in template rather than extending JS class
  ember-bootstrap/addon/components/bs-dropdown/button.hbs
  ember-bootstrap/addon/components/bs-dropdown/button.js
Labels: internal

#2125 invalid syntax in docs example for form component
  ember-bootstrap/addon/components/bs-form/element.js
Labels: documentation
