Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2024-05, with the labels that each got.

#2127 Fix syntax in BsForm API docs
  ember-bootstrap/addon/components/bs-form.js
Labels: documentation

#2130 allow action helper and modifier deprecation for now
  test-app/tests/helpers/setup-no-deprecations.ts
Labels: internal

#2129 Styling of toggle button yielded by BsDropdown via arguments is ignored
  ember-bootstrap/addon/components/bs-dropdown/button.hbs
  test-app/tests/integration/components/bs-dropdown/button-test.js
Labels: bug
