Repository ember-bootstrap/ember-bootstrap, pull requests merged in 2024-02, with the labels that each got.

#2077 Fix several issues with BsCarousel component
  ember-bootstrap/addon/components/bs-carousel.hbs
  ember-bootstrap/addon/components/bs-carousel.js
  ember-bootstrap/addon/components/bs-carousel/slide.hbs
  ember-bootstrap/addon/components/bs-carousel/slide.js
  test-app/tests/integration/components/bs-carousel-test.js
Labels: bug

#2083 Deprecate inserting wormhole target
  docs/app/templates/getting-started/setup.hbs
  ember-bootstrap/addon/utils/dom.js
  ember-bootstrap/index.js
Labels: enhancement, documentation

#2097 Run Safari tests after basic tests
  .github/workflows/ci.yml
Labels: internal

#2094 [docs] Resolve remaining lint warnings
  docs/.eslintrc.js
  docs/.template-lintrc.js
  docs/app/templates/demo/alert.hbs
  docs/app/templates/demo/modal.hbs
  docs/app/templates/demo/navbars.hbs
  docs/app/templates/demo/navs.hbs
  docs/app/templates/demo/popover.hbs
  docs/app/templates/demo/progress.hbs
  docs/app/templates/demo/tabs.hbs
  docs/app/templates/index.hbs
  docs/tests/acceptance/addons-test.js
  docs/tests/acceptance/components-test.js
  docs/tests/acceptance/components/accordion-test.js
  docs/tests/acceptance/components/alert-test.js
  docs/tests/acceptance/components/button-group-test.js
  docs/tests/acceptance/components/button-test.js
  docs/tests/acceptance/components/carousel-test.js
  docs/tests/acceptance/components/collapse-test.js
  docs/tests/acceptance/components/dropdown-test.js
  docs/tests/acceptance/components/forms-test.js
  docs/tests/acceptance/components/list-group-test.js
  docs/tests/acceptance/components/modal-test.js
  docs/tests/acceptance/components/navbars-test.js
  docs/tests/acceptance/components/navs-test.js
  docs/tests/acceptance/components/popover-test.js
  docs/tests/acceptance/components/progress-test.js
  docs/tests/acceptance/components/spinner-test.js
  docs/tests/acceptance/components/tabs-test.js
  docs/tests/acceptance/components/tooltip-test.js
  docs/tests/acceptance/getting-started-test.js
  docs/tests/acceptance/getting-started/assets-test.js
  docs/tests/acceptance/getting-started/setup-test.js
  docs/tests/acceptance/index-test.js
Labels: internal

#2093 Convert BsButton to TypeScript
  .vscode/settings.json
  ember-bootstrap/.eslintignore
  ember-bootstrap/.gitignore
  ember-bootstrap/addon/components/bs-button.hbs
  ember-bootstrap/addon/components/bs-button.ts
  ember-bootstrap/addon/helpers/bs-size-class.ts
  ember-bootstrap/addon/helpers/bs-type-class.ts
  ember-bootstrap/addon/template-registry.ts
  ember-bootstrap/addon/utils/decorators/arg.js
  ember-bootstrap/addon/utils/decorators/arg.ts
  ember-bootstrap/package.json
  ember-bootstrap/tsconfig.declarations.json
  ember-bootstrap/tsconfig.json
  ember-bootstrap/types/glint.d.ts
  ember-bootstrap/types/global.d.ts
  ember-bootstrap/types/macros-config.d.ts
  package.json
  pnpm-lock.yaml
  test-app/app/config/environment.d.ts
  test-app/config/environment.js
  test-app/package.json
  test-app/tests/helpers/assert-errors.js
  test-app/tests/helpers/assert-errors.ts
  test-app/tests/helpers/bootstrap.ts
  test-app/tests/helpers/contextual-help.ts
  test-app/tests/helpers/defer.js
  test-app/tests/helpers/defer.ts
  test-app/tests/helpers/index.ts
  test-app/tests/helpers/setup-no-deprecations.ts
  test-app/tests/helpers/setup-stylesheet-support.js
  test-app/tests/helpers/setup-stylesheet-support.ts
  test-app/tests/helpers/user-agent.ts
  test-app/tests/integration/components/bs-button-test.ts
  test-app/tests/integration/components/bs-tooltip-test.js
  test-app/types/glint.d.ts
  test-app/types/global.d.ts
Labels: enhancement

#2100 Fix click events inside `bs-dropdown`s not activating
  ember-bootstrap/addon/components/bs-dropdown.js
  test-app/ember-cli-build.js
  test-app/tests/integration/components/bs-dropdown-test.js
Labels: bug

#2099 Convert BsLinkTo to TypeScript
  ember-bootstrap/addon/components/bs-dropdown/menu.hbs
  ember-bootstrap/addon/components/bs-link-to.hbs
  ember-bootstrap/addon/components/bs-link-to.ts
  ember-bootstrap/addon/components/bs-nav.hbs
  ember-bootstrap/addon/components/bs-navbar.hbs
  ember-bootstrap/addon/components/bs-navbar/link-to.hbs
Labels: enhancement

#2091 Deprecate `importBootstrapCSS`, remove `importBootstrapTheme` and `importBootstrapFont`
  docs/app/templates/getting-started/assets.hbs
  docs/app/templates/getting-started/setup.hbs
  ember-bootstrap/blueprints/ember-bootstrap/index.js
  ember-bootstrap/index.js
  ember-bootstrap/node-tests/blueprints/ember-bootstrap-test.js
Labels: enhancement

#2108 Convert BsSpinner to TypeScript
  ember-bootstrap/addon/components/bs-spinner.hbs
  ember-bootstrap/addon/components/bs-spinner.ts
  ember-bootstrap/addon/template-registry.ts
  test-app/tests/integration/components/bs-spinner-test.ts
Labels: enhancement
